name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no Dashboard.py GymCleanData.csv ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/streamlit_app/

    - name: Restart Streamlit App
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
        source /home/ubuntu/streamlit_app/env/bin/activate
        cd /home/ubuntu/streamlit_app
        pkill -f streamlit || true  # Detener cualquier instancia previa de Streamlit
        nohup streamlit run Dashboard.py --server.port 8501 --server.headless true > streamlit.log 2>&1 &
        exit
        EOF
