name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy Streamlit App to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
        sudo apt update
        sudo apt install python3-pip -y
        mkdir -p /home/ubuntu/streamlit_app
        exit
        EOF

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no Dashboard.py requirements.txt ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/streamlit_app/

    - name: Install Dependencies and Run Streamlit
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
        cd /home/ubuntu/streamlit_app
        pip install -r requirements.txt
        nohup streamlit run Dashboard.py --server.port 8501 --server.headless true &
        exit
        EOF
